name: CI

on:
  pull_request:
    branches:
      - main

jobs:
    bonsai-interface:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v4.0.0
              with:
                dotnet-version: 8.x

            - name: Regenerate Bonsai Interface
              run: dotnet build ./Generators

            - name: Check uncommitted changes
              run: |
                git config --global core.safecrlf false
                git diff --exit-code || (echo "Untracked changes found while regenerating Bonsai interface" && exit 1)