name: Harp.Behavior
on:
  push:
    # This prevents tag pushes from triggering this workflow
    branches: ['**']
  pull_request:
  release:
    types: [published]
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  ContinuousIntegrationBuild: true
  AVR_TOOLCHAIN_URL: https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-3.6.2.1778-win32.any.x86.zip
jobs:
  build-firmware:
    strategy:
      fail-fast: false
      matrix:
        hardware-target: ['1.1', '1.2', '2.0']
    name: Build Firmware (hw${{matrix.hardware-target}})
    runs-on: windows-latest
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------------------------------------- Set up tools
      - name: Set up AVR-GCC
        run: |
          Invoke-WebRequest -Uri $env:AVR_TOOLCHAIN_URL -OutFile $HOME\avr8-gnu-toolchain-win32_x86_64.zip
          Expand-Archive $HOME\avr8-gnu-toolchain-win32_x86_64.zip -DestinationPath $HOME -Force
          echo "$(Resolve-Path $HOME\avr8-gnu-toolchain-win32_x86\bin)" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # ----------------------------------------------------------------------- Configure build
      - name: Configure build
        id: configure-build
        uses: harp-tech/configure-build@v1

      # ----------------------------------------------------------------------- Build firmware
      - name: Build firmware
        working-directory: Firmware/Behavior
        id: build
        shell: bash
        run: make all FIRMWARE_VERSION=${{env.CiBuildVersion}} HARDWARE_VERSION=${{matrix.hardware-target}} PREVIEW_VERSION=${{env.CiFirmwarePreviewVersion}}

      # ----------------------------------------------------------------------- Collect artifacts
      - name: Collect Firmware binaries
        uses: actions/upload-artifact@v4
        if: steps.build.outcome == 'success' && always()
        with:
          name: Firmware-hw${{matrix.hardware-target}}
          if-no-files-found: error
          path: Firmware/Behavior/bin/*.hex

      # ----------------------------------------------------------------------- Upload release assets
      - name: Upload release assets
        if: github.event_name == 'release'
        run: gh release upload --repo ${{github.repository}} ${{github.event.release.tag_name}} Firmware/Behavior/bin/*.hex --clobber
        env:
          GH_TOKEN: ${{github.token}}

  build-interface:
    strategy:
      fail-fast: false
      matrix:
        configuration: ['Release']
        include:
          - configuration: Release
            collect-packages: true
    name: Build Interface
    runs-on: windows-latest
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------------------------------------- Set up tools
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Set up .NET tools
        run: dotnet tool restore

      # ----------------------------------------------------------------------- Configure build
      - name: Configure build
        id: configure-build
        uses: harp-tech/configure-build@v1

      # ----------------------------------------------------------------------- Regenerate
      - name: Run generators
        run: dotnet harp.toolkit generate interface -o Interface/${{github.workflow}}

      - name: Verify pre-generated code was up-to-date
        id: verify-dist
        run: |
          git add . --intent-to-add --ignore-removal
          git diff --name-status --exit-code

      # ----------------------------------------------------------------------- Build interface package
      - name: Restore interface
        run: dotnet restore Interface

      - name: Build interface
        run: dotnet build Interface --no-restore --configuration ${{matrix.configuration}}

      - name: Pack interface
        id: pack
        run: dotnet pack Interface --no-restore --no-build --configuration ${{matrix.configuration}}

      # ----------------------------------------------------------------------- Collect artifacts
      - name: Collect NuGet packages
        uses: actions/upload-artifact@v4
        if: matrix.collect-packages && steps.pack.outcome == 'success' && always()
        with:
          name: Packages
          if-no-files-found: error
          path: Interface/bin/${{matrix.configuration}}/**

      # ----------------------------------------------------------------------- Upload release assets
      - name: Upload release assets
        if: github.event_name == 'release' && matrix.configuration == 'Release'
        run: gh release upload --repo ${{github.repository}} ${{github.event.release.tag_name}} Interface/bin/${{matrix.configuration}}/** --clobber
        env:
          GH_TOKEN: ${{github.token}}

  publish-packages-nuget-org:
    name: Publish packages to NuGet.org
    runs-on: ubuntu-latest
    permissions:
      # Needed to attach files to releases
      contents: write
    environment: public-release
    needs: [build-firmware, build-interface]
    if: github.event_name == 'release'
    steps:
      # ----------------------------------------------------------------------- Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      # ----------------------------------------------------------------------- Download built packages
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: artifacts/packages/

      # ----------------------------------------------------------------------- Push to NuGet.org
      - name: Push to NuGet.org
        run: dotnet nuget push "artifacts/packages/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source ${{vars.NUGET_API_URL}}
        env:
          # This is a workaround for https://github.com/NuGet/Home/issues/9775
          DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0
